//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sefa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAY
    {
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> U1_AKTIF { get; set; }
        public Nullable<int> U1_REAKTIF { get; set; }
        public Nullable<int> U2_AKTIF { get; set; }
        public Nullable<int> U2_REAKTIF { get; set; }
        public Nullable<int> U3_AKTIF { get; set; }
        public Nullable<int> U3_REAKTIF { get; set; }
        public Nullable<int> ENERJI { get; set; }
        public int ID { get; set; }
    }
}
