//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sefa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class saastek_dbEntities : DbContext
    {
        public saastek_dbEntities()
            : base("name=saastek_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARISU> ARISU { get; set; }
        public virtual DbSet<CAY> CAY { get; set; }
        public virtual DbSet<ZALA> ZALA { get; set; }
    }
}
